swagger: '2.0'
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /:
    get:
      summary: x
      description: x
      produces:
        - x
      responses:
        200:
          description: OK
definitions:
  Order:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      petId:
        type: 'integer'
        format: 'int64'
      quantity:
        type: 'integer'
        format: 'int32'
      shipDate:
        type: 'string'
        format: 'date-time'
      status:
        type: 'string'
        description: 'Order Status'
        enum:
          - 'placed'
          - 'approved'
          - 'delivered'
      complete:
        type: 'boolean'
        default: false
    xml:
      name: 'Order'
  Category:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
    xml:
      name: 'Category'
